version: "3"

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    command: --replSet rs0
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

volumes:
  db_data: { }
